### ISSUE TITLE
IllegalStateException thrown when JavaScript resource is opened

### ISSUE THREAD

**Issue by sstyana** [cypher256/eclipse-encoding-plugin#9]
Environment: Pleiades All in One Java, Oxygen (Windows 64bit)

Steps:

1. Switch to JavaEE perspective
2. Make new JavaScript project
3. Open any item under "JavaScript resource" - "ECMAScript built-in library"
4. IllegalStateException thrown

```
java.lang.IllegalStateException: java.lang.NoSuchMethodException: org.eclipse.wst.jsdt.internal.core.LibraryFragmentRoot.getRawClasspathEntry()
	at mergedoc.encoding.JarResource.setPackageFragmentRoot(JarResource.java:53)
	at mergedoc.encoding.document.ClassFileJarDocument.updateStatus(ClassFileJarDocument.java:51)
	at mergedoc.encoding.document.ActiveDocument.init(ActiveDocument.java:66)
	at mergedoc.encoding.document.ClassFileJarDocument.init(ClassFileJarDocument.java:35)
	at mergedoc.encoding.document.ActiveDocument.<init>(ActiveDocument.java:52)
	at mergedoc.encoding.document.ClassFileJarDocument.<init>(ClassFileJarDocument.java:24)
	at mergedoc.encoding.ActiveDocumentAgent.getDocument(ActiveDocumentAgent.java:128)
```
ActiveDocumentAgent.getDocument() seems confused with
org.eclipse.jdt.internal.ui.javaeditor.InternalClassFileEditorInput (Java editor)
and
org.eclipse.wst.jsdt.internal.ui.javaeditor.InternalClassFileEditorInput (JavaScript editor).

Possible fix (I've not tried):

at ActiveDocumentAgent.getDocument(), change
`} else if (editorInput.getClass().getSimpleName().equals("InternalClassFileEditorInput")) {
`
to
`} else if (editorInput.getClass().getName().equals("org.eclipse.jdt.internal.ui.javaeditor.InternalClassFileEditorInput")) {
`

[event.txt](https://github.com/cypher256/eclipse-encoding-plugin/files/1643259/event.txt)

**Comment by cypher256** [comment]
Fix open error item in "ECMAScript built-in library".
1.8.5 - 2018.01.19
Thanks for the detailed report.

**Comment by sstyana** [comment]
I tried 1.8.5, and confirmed the issue was solved.
Thanks for quick response.
